#Kafka Topic Name
audit:
  kafka:
    topic:
      shipment-note: ${KAKFA_SHIPMENT_NOTE_TOPIC}
      audit-trail: ${KAKFA_AUDIT_TRAIL_TOPIC}

#kafka bootstrap server
kafka:
  client-id:
  bootstrap-servers: ${BOOKING_SERVER}
  schema-registry:
    url: ${SCHEMA_URL}
    username:
    password: